name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t kayzaarya/ecommerce-app .

    - name: Dummy Unit Test
      run: echo "Semua pengujian unit berhasil ✅"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      run: docker push kayzaarya/ecommerce-app

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull kayzaarya/ecommerce-app
          docker stop ecommerce-container || true
          docker rm ecommerce-container || true
          docker run -d -p 80:80 --name ecommerce-container kayzaarya/ecommerce-app
